### ISSUE TITLE
Wrong data

### ISSUE THREAD

**Issue by tienrocker** [parsilver/thailand-provinces#2]
In your SQL file, please give me more detail about number '97', how to mapping to another table?

`(462, '4303', 'เมืองบึงกาฬ', 'Mueang Bueng Kan', 97)`

in json data :
`{"id":"462","code":"4303","name_th":"เมืองบึงกาฬ","name_en":"Mueang Bueng Kan","province_id":"97"}`

**Comment by parsilver** [comment]
It's duplicate data, I have fixed by delete duplicate data (Duplicate with province_id = 77).

Thank you for submit. ^^
