### ISSUE TITLE
รายชื่ออำเภอไม่ถูกต้อง

### ISSUE THREAD

**Issue by anantapon** [parsilver/thailand-provinces#5]
ในตาราง amphurs name_th ที่ชื่อ *บ้านทะวาย มี province_id เป็น กทม. นี่คืออะไรครับ
สังเกตเห็นว่าชื่อที่มี * (ดอกจัน) ต่อท้ายชื่อมักจะไม่ถูก เช่น อ.บ้านหัน จ.สกลนคร อื่นๆผมไม่แน่ใจว่าข้อมูลมีความถูกต้องไม๊
ข้อมูลพวกนี้คุณไปเอามาจากไหนครับ? ของทราบแหล่งที่มาด้วยครับ

ขอบคุณครับ

**Comment by parsilver** [comment]
ขอโทษด้วยนะครับพี่ที่ตอบช้า
โดยข้อมูลหลักผมเอามาจากเว็บ www.ssckp.org ครับ ก่อนที่เว็บนี้ปิดตัวครับ
ซึ่งมันก็นานมากแล้ว

หลังจากนั้นผมก็ไม่ค่อยได้อัพเดดครับ

```
* คือ อาจเป็นกิ่งอำเภอ หรือ ข้อมูลที่ยังแน่นอน
และตอนนี้น่าจะเปลี่ยนไปเยอะแล้ว
```

ถ้าพี่พบเจออะไรแปลกๆ
เดี๋ยวผมจะตรวจสอบและแก้ไขให้นะครับ
หรือพี่ส่ง pull request ให้ได้เลยนะครับ

ขอบคุณครับ
